// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzrLKKXfHl5Lfzyt7tE-pQ6d82D-_-67Y',
    appId: '1:869861670780:web:785ca317636c7db41a6ef9',
    messagingSenderId: '869861670780',
    projectId: 'testpro-73a93',
    authDomain: 'testpro-73a93.firebaseapp.com',
    storageBucket: 'testpro-73a93.firebasestorage.app',
    measurementId: 'G-YMRVVW1N1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWz_j_34aRy9BrRnuZNr2oSQKLBCdMHuA',
    appId: '1:869861670780:android:b8d27c93bbec215a1a6ef9',
    messagingSenderId: '869861670780',
    projectId: 'testpro-73a93',
    storageBucket: 'testpro-73a93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6NSb4lzLTHFJKRJG5Q4z6XMgBU57g0m4',
    appId: '1:869861670780:ios:5baf68f15b1ca1591a6ef9',
    messagingSenderId: '869861670780',
    projectId: 'testpro-73a93',
    storageBucket: 'testpro-73a93.firebasestorage.app',
    iosBundleId: 'com.example.testpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6NSb4lzLTHFJKRJG5Q4z6XMgBU57g0m4',
    appId: '1:869861670780:ios:5baf68f15b1ca1591a6ef9',
    messagingSenderId: '869861670780',
    projectId: 'testpro-73a93',
    storageBucket: 'testpro-73a93.firebasestorage.app',
    iosBundleId: 'com.example.testpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzrLKKXfHl5Lfzyt7tE-pQ6d82D-_-67Y',
    appId: '1:869861670780:web:b491ea5aa7b0ddef1a6ef9',
    messagingSenderId: '869861670780',
    projectId: 'testpro-73a93',
    authDomain: 'testpro-73a93.firebaseapp.com',
    storageBucket: 'testpro-73a93.firebasestorage.app',
    measurementId: 'G-KM9QPL6Y4J',
  );

}